[project]
name = "llm-post-training-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yichen Shen", email = "ycshen0117@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
llm-post-training-lab = "llm_post_training_lab:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "ruff>=0.16.5",
]

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.pytest.ini_options]
testpaths = ["tests"]
